### ISSUE TITLE
Version for Discord

### ISSUE THREAD

**Issue by ultimatecheese** [thisiscam/math-with-slack#13]
This is not an _issue_, more a "fork request". (I could not see a better place for writing this, though.)

How easy do you think it would be to make this work for Discord? It seems to me that the underlying structures of the two are fairly similar. Perhaps a Discord version wouldn't be so difficult?

Of course, I could be completely mistaken.

**Comment by thisiscam** [comment]
It is possible. 

These the required steps to do what you proposed:
- find the entry point in app.asar
- locate the class decorator for the chat messages, so that MathJax can be injected

The second step seems pretty easy, since Discord App has the developer menu option. 

For the first step I downloaded discord and unpacked its `app.asar`. But I was not able to find an entry point where I can get access to the main window. For some reason `app_bootstrap/bootstrap.js` is the most suspicious, but it doesn't seem to do what I expect it to. 

If anyone idea has for the above, I can adjust the code to also work for Discord!

**Comment by thisiscam** [comment]
Closing since I don't think there's anything to be done here rn. 
Please reopen if you have more ideas.
