### ISSUE TITLE
`math-with-slack` results in "slack quite unexpectedly" error

### ISSUE THREAD

**Issue by RyanK0902** [thisiscam/math-with-slack#43]
Everytime I run `math-with-slack.py` (even with the `--codesign` flag), I always get an error that looks like below
![Screen Shot 2022-05-11 at 6 34 38 PM](https://user-images.githubusercontent.com/79249503/167974747-a40d7a63-2b3a-4bb3-be80-96b3a2a7144b.png)
Any idea why this is happening?

**Comment by thisiscam** [comment]
Is Slack closed when you run the script?

**Comment by RyanK0902** [comment]
yes it is

**Comment by thisiscam** [comment]
There had been several updates since the issue was posted. Can you try again with the latest version?
~~This seems to be related to code signing. What is your system version?~~

Nevermind, your screenshot says it is 11.5.2. I suspect this is due to the current code signing only supports macOS 12. (due to some bug, perhaps). I will look into this

**Comment by thisiscam** [comment]
https://github.com/thisiscam/math-with-slack/commit/52657ef3abe93c412498d5a7575720004f4f57b5 might or might not fix this problem. Could you try again with latest master?
